<a href="https://colab.research.google.com/github/MalikHasnat1999/ZTM_Tensorflow/blob/master/00_Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **We are going to cover the following Topics**
---

# Introduction to Tensors

In [ ]:
# Tensorflow
import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
# creating Tensor using tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Checking the demnsion of tensor(ndim number of dimensions)
scalar.ndim

0

In [ ]:
# creating a vector
vector = tf.constant([2,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
# dimention of vector
vector.ndim

1

In [ ]:
# matrix
matrix = tf.constant([[1,2,2],
                      [3,4,6],
                      [1,1,1]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 2],
       [3, 4, 6],
       [1, 1, 1]], dtype=int32)>

In [ ]:
# dimenstions of a matrix
matrix.ndim

2

In [ ]:
# Creating another matrix
another = tf.constant([[1.,2.],
                      [3.,4.],
                      [7.,8.]], dtype=tf.float16) # specifying the Data type
another

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [7., 8.]], dtype=float16)>

In [ ]:
another.ndim
# dimension is how many elements are in shape()

2

In [ ]:
# lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [2,3,4]],
                      [[3,3,3],
                       [4,4,4]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what've created so far

* scalar: a single number
* vector: a number with direction(e.g wind speed with direction) 
* Matrix: 2-dimensional array of numbers
* Tensor: is n-dimensional array of numbers

#### Changeable and unchangeable Tensors

---



In [ ]:
changeable_tensor = tf.Variable([1,1])
unchangeable_tensor = tf.constant([3,4])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [ ]:
# lets try changing the tensors
# using assign()

changeable_tensor[1].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [ ]:
 # lets try changing the unchangeable tensor

# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

# we cannot change the constant() tensors 

# Creating Random Tensors

Random Tensors are of arbitrary size which contain random numbers

In [ ]:
# creating two random(but same) tensors
# seed() gives the same random numbers
random_1 = tf.random.Generator.from_seed(10)
random_1 = random_1.uniform(shape=(2,2))
random_2 = tf.random.Generator.from_seed(10)
random_2 = random_2.normal(shape=(2,2))

# Are they two equal?
print(random_1),print(random_2), print(random_1 == random_2)

tf.Tensor(
[[0.93598676 0.6513264 ]
 [0.31663585 0.00111556]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.29604465 -0.21134205]
 [ 0.01063002  1.5165398 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


(None, None, None)

### shuffling the order of Random Tensors

In [ ]:
# valuable when you want to shuffle your data so the inherent order doesn't
not_shuffled = tf.constant([[1,1],
                            [2,2],
                            [3,3]])
# shuffling
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [1, 1],
       [2, 2]], dtype=int32)>

Using argument set_seed()
* Global level seed
      tf.random.set_seed(7)
* Operational level seed
      tf.random.shuffle(not_shuffled, seed=7)

#### **Rules**

In [ ]:
# 1-If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [1, 1],
       [2, 2]], dtype=int32)>

In [ ]:
# 2-If the global seed is set, but the operation seed is not: The system deterministically picks an operation
#   seed in conjunction with the global seed so that it gets a unique random sequence.
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled)

# As global seed is set so the Random order will be always same

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 3],
       [1, 1]], dtype=int32)>

In [ ]:
# 3-If the operation seed is set, but the global seed is not set: A default global seed and the specified
#   operation seed are used to determine the random sequence.
tf.random.shuffle(not_shuffled, seed=7)

# global seed is not set but op seed is set so random order is different always

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [1, 1],
       [3, 3]], dtype=int32)>

In [ ]:
# 4-If both the global and the operation seed are set: Both seeds are used in conjunction to determine the 
#   random sequence.
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled, seed=7)

# Random order is always same

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [1, 1],
       [3, 3]], dtype=int32)>

# Other ways of making Tensors

> .ones()

In [ ]:
# Creating Tensor of all Ones
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

> .zeros()

In [ ]:
# creating Tensor of all zeros
tf.zeros([3,3])
# OR
tf.zeros(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

## Turn Numpy arrays into Tensors
The main difference between numpy array and Tensorflow tensors is that tensor can run on GPU(much  faster for nummerical computing)

In [ ]:
# You can also convert numpy array into Tensors
import numpy as np

# creating a numpy array
np.arange(1,25) # create a numpy array b/w 1,25

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# conversion to Tensor
A = tf.constant(np.arange(1,25))
A

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
# Changing the shape of the Tensor
tf.constant(A, shape=(4,6))

# why 4,6?
# cause 4*6=24  that is the size of our Tensor
# it can also be 2*3*4=24(0-24)

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])>


# 19.Getting Information from Tensors
---



When dealing with the tensor you probably want to be aware of the following attributes:
* Shape 
> tensor.shape
* Rank
> tensor.ndim
* Axis
> tensor[0], tensor[: , 1]...
* Size
> tf.size(tensor)

In [ ]:
# Creating a Rank 4 tensor (4 Dimensions)
rank_4 = tf.zeros(shape=[2,3,4,5])
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Axis
rank_4[:,0]


<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4.ndim, rank_4.shape, tf.size(rank_4)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
# Getting various attributes of tensor
print("Data Type of Tensor", rank_4.dtype)
print("Number of Dimensions", rank_4.ndim)
print("Shape of Tensor", rank_4.shape)
print("Elemets along 0 axis", rank_4.shape[0])
print("Elemets along last axis", rank_4.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4))
print("Total number of elements in our tensor:", tf.size(rank_4).numpy())

Data Type of Tensor <dtype: 'float32'>
Number of Dimensions 4
Shape of Tensor (2, 3, 4, 5)
Elemets along 0 axis 2
Elemets along last axis 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


# 20.Indexing and Expanding Tensors

Tensors can be listed just like Python lists.

In [ ]:
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Getting first 2 elements of each Dimension
# in lists
dummy = [1,2,4,5,6,7]
dummy[:2]

[1, 2]

In [ ]:
# in Tensors
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4.shape

TensorShape([2, 3, 4, 5])

In [ ]:
# Get the first Element from the each diemension except for the final dimension
rank_4[:1,:1,:1,:]

# : means except for this 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[1,2,3],
                             [4,5,6]]) # 2-dimensions
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# Get last item of the rank 2 Tensors
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [ ]:
# Adding Extra dimension at the end of the tensor
# tf.newaxis
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

# OR
# rank_3_tensor = rank_2_tensor[..., tf.newaxis]

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [ ]:
# Alternate of tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)   # -1 means expand the final Dimension

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # 0 means expand from start

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

# 21.Manipulating Tensors(Tensors operations)

**Basic Operaitons**
`+`,`-`,`*`,`/`

In [ ]:
tensor = tf.constant([[1,2,3],
                      [3,4,5]])
tensor + 1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tensor - 1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 3, 4]], dtype=int32)>

In [ ]:
tensor / 2

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])>

In [ ]:
# we can also use the tensor built-in funcitions
# Recommended using these functions
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 6,  8, 10]], dtype=int32)>

In [ ]:
tf.add(tensor, 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# etc

# 22.Matrix Multiplicaiton of Tensors


In machine learning, matric multiplication(Dot Product) is one 

---

the most common tensor operations

There are Two Rules our Tensor must fulfill
1. inner Dimension must match
2. The resulting matrix has shape of the inner matrix

We can perform the matrix multiplication using 
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
tensor = tf.constant([[1,2,3],
                      [4,5,6],
                      [5,6,7]])
tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]], dtype=int32)>

In [ ]:
# Matrix multiplication 
tf.tensordot(tensor, tensor, axes=1), tf.matmul(tensor, tensor)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 24,  30,  36],
        [ 54,  69,  84],
        [ 64,  82, 100]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 24,  30,  36],
        [ 54,  69,  84],
        [ 64,  82, 100]], dtype=int32)>)

In [ ]:
# simple multiplication
tensor * tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [25, 36, 49]], dtype=int32)>

In [ ]:
# Matrix Multipilcation(Dot Product)e using python operator '@
tensor @ tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 24,  30,  36],
       [ 54,  69,  84],
       [ 64,  82, 100]], dtype=int32)>

In [ ]:
# If matrix is unfit for multiplication
matrix = tf.constant([[1,2],
                       [4,6],
                       [1,1]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 6],
       [1, 1]], dtype=int32)>

In [ ]:
# reshaping the matrix
# first we reshape the matrix from 3x2 to 2x3 then multiply it
tf.matmul(matrix, tf.reshape(matrix, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13,  4,  6],
       [40, 14, 22],
       [ 7,  3,  5]], dtype=int32)>

In [ ]:
# Dot Product using Python operator '@'
matrix @ tf.reshape(matrix, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13,  4,  6],
       [40, 14, 22],
       [ 7,  3,  5]], dtype=int32)>

In [ ]:
# Difference b/w Transpose() and Reshape()
# Transpose Flips the Axis rather than shuffling the elements (Both changes the shape)
matrix, tf.transpose(matrix), tf.reshape(matrix, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 6],
        [1, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 4, 1],
        [2, 6, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [6, 1, 1]], dtype=int32)>)

In [ ]:
# Using tf.tensordot()
tf.tensordot(tf.transpose(matrix), matrix, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 27],
       [27, 41]], dtype=int32)>

In [ ]:
tf.tensordot(matrix, tf.transpose(matrix), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 16,  3],
       [16, 52, 10],
       [ 3, 10,  2]], dtype=int32)>

In [ ]:
# Using Reshape
tf.tensordot(tf.reshape(matrix, shape=(2,3)), matrix, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 18],
       [11, 19]], dtype=int32)>

In [ ]:
####
# Always use Transpose Rather than Reshape
####

# 25.Changing the Datatype of the Tensor
---




In [ ]:
# Creating a tensor using the default datatype
x = tf.constant([1,2,3])
x.dtype

tf.int32

In [ ]:
# Change from int32 to int16
x = tf.cast(x, dtype=tf.int16)
x.dtype

tf.int16

In [ ]:
x = tf.cast(x, dtype=tf.float16)
x.dtype

tf.float16

# 26.Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to smaller amount of values

In [ ]:
# Absolute Values
x = tf.constant([1,-2,-3,4])
tf.abs(x)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

Lets go through from the following forms of Aggergation
* Get minimum value
* Get maximum value
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# create a random tensor 
tensor = tf.constant(np.random.randint(0,100, size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([30, 89,  6,  1, 27, 68, 16, 53, 51, 47, 99, 72, 66, 79, 47, 96, 65,
       86, 29, 42, 74, 70, 96, 19, 37, 23, 29, 17, 66, 25, 17, 91, 66, 78,
       18, 77, 84, 67, 28, 68,  9, 89, 16, 64, 52, 84,  9, 81, 43, 14])>

In [ ]:
# Finding the maximum value
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Finding the minimum value
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Finding the mean
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
# Finding the sum
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2580>

In [ ]:
# Finding the variance and Standard Deviation?
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=823>

In [ ]:
# Statndard Deviation
tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.694948>

In [ ]:
# OR
# Variance
tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=823.4>

### 28. Positional Maximum and Minimum

In [ ]:
# Creating new Tensor
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Finding positional Maximum
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Find the value at position 
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Finding Maximum
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Are they Equal?
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Finding Positional Minimum
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Finding value at the position
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# Finding the minimum value
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# Are they both Equal?
tensor[tf.argmin(tensor)] == tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a Tensor

* Removes dimensions of size 1 from the shape of a tensor

In [ ]:
# Creating a tensor
tf.random.set_seed(42)
A = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
A

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
A.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# Squeezing the tensor
tf.squeeze(A).shape


TensorShape([50])

# 30.One-hot encoding Tensor

In [ ]:
# Create a list 
my_list = [1, 2, 3]

# Creating one_hot
# Takes Tensor of indices
tf.one_hot(my_list, depth=4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Adding On and Off values
tf.one_hot(my_list, depth=3, on_value='yes', off_value='No')

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'No', b'yes', b'No'],
       [b'No', b'No', b'yes'],
       [b'No', b'No', b'No']], dtype=object)>

# 32.Tensors and Numpy

Tensorflow interacts beautifully with Numpy arrays
* The main difference b/w tensor and numpy array is that tensors run faster on GPU or TPU

In [ ]:
# creating Tensor from numpy array
tensor = tf.constant(np.array([1., 2., 3.]))
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
# Convert Tensor back to numpy array
np.array(tensor)

array([1., 2., 3.])

In [ ]:
# Convert Tensor back to numpy array (other method)
tensor.numpy()

array([1., 2., 3.])

In [ ]:
# Default Types
tensor = tf.constant([1.,2.,3.])
numpy_tensor = tf.constant(np.array([1.,2.,3.]))

tensor.dtype, numpy_tensor.dtype

(tf.float32, tf.float64)

# Accessing GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# **Exercise**

In [ ]:
# 1-Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
# Scalar
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
# vector
vector = tf.constant([2,3,4])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
# Matrix
matrix = tf.constant([[23,42,2],
             [1,23,4]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[23, 42,  2],
       [ 1, 23,  4]], dtype=int32)>

In [ ]:
# 2-Find the shape, rank and size of the tensors you created in 1.
# Rank
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [ ]:
# shape
scalar.shape, vector.shape, matrix.shape

(TensorShape([]), TensorShape([3]), TensorShape([2, 3]))

In [ ]:
# size
tf.size(scalar), tf.size(vector), tf.size(matrix)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [ ]:
# 3-Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor_1 = tf.random.uniform(shape=(5,300))
tensor_2 = tf.random.uniform(shape=(5,300))
tensor_1, tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

In [ ]:
# 4-Multiply the two tensors you created in 3 using matrix multiplication
tf.matmul(tensor_1, tf.reshape(tensor_2, shape=(300,5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.742355, 78.96601 , 76.4375  , 79.90297 , 79.41223 ],
       [73.00635 , 70.02398 , 70.02371 , 72.228424, 70.10681 ],
       [78.79178 , 78.55487 , 75.45839 , 77.58642 , 74.710556],
       [75.785736, 74.37855 , 71.91179 , 73.319595, 71.63658 ],
       [84.22469 , 77.5869  , 79.075005, 81.65291 , 77.13225 ]],
      dtype=float32)>

In [ ]:
# OR
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71401 , 80.87824 , 78.32848 , 78.2597  , 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.2774  ],
       [75.16001 , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.11356 , 75.401215, 72.79378 , 75.066376, 75.20653 ],
       [79.87285 , 83.40139 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [ ]:
# 5-Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71401 , 80.87824 , 78.32848 , 78.2597  , 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.2774  ],
       [75.16001 , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.11356 , 75.401215, 72.79378 , 75.066376, 75.20653 ],
       [79.87285 , 83.40139 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [ ]:
# OR
tf.tensordot(tensor_1, tf.reshape(tensor_2, shape=(300, 5)), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.742355, 78.96601 , 76.4375  , 79.90297 , 79.41223 ],
       [73.00635 , 70.02398 , 70.02371 , 72.228424, 70.10681 ],
       [78.79178 , 78.55487 , 75.45839 , 77.58642 , 74.710556],
       [75.785736, 74.37855 , 71.91179 , 73.319595, 71.63658 ],
       [84.22469 , 77.5869  , 79.075005, 81.65291 , 77.13225 ]],
      dtype=float32)>

In [ ]:
# 6-Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor = tf.random.normal(shape=(224,224,3))
tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.65648675, -0.4130517 ,  0.33997506],
        [-1.0056272 ,  0.70266235, -1.4008642 ],
        [-0.89780754, -0.34856176, -0.95890623],
        ...,
        [ 1.0194341 ,  0.74672526,  0.39955083],
        [-0.7627328 ,  0.45062128,  1.3667524 ],
        [ 0.11498784,  0.5782295 ,  0.78359014]],

       [[-0.06949335, -0.23398751,  0.7211032 ],
        [-0.0861904 ,  1.5687186 , -0.4009926 ],
        [ 1.3798339 ,  0.74632597, -0.11167198],
        ...,
        [ 1.3134544 , -0.2631335 , -1.0683311 ],
        [ 0.12667303,  0.08279036, -0.9775129 ],
        [-0.14422436,  2.7495377 ,  1.6180834 ]],

       [[-0.93781394,  0.10042718,  1.279594  ],
        [ 0.87256527,  1.8590354 , -0.2577575 ],
        [-1.0056995 , -1.1477438 ,  1.2598884 ],
        ...,
        [ 0.78982466,  1.1393182 , -0.2799689 ],
        [ 0.44983366, -1.4157982 ,  1.3792404 ],
        [ 1.8690307 , -1.1984336 , -0.5294158 ]],

       ...,

     

In [ ]:
# 7-Find the min and max values of the tensor you created in 6 along the first axis.
# Minimum
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.5823126>

In [ ]:
# Max
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=4.118299>

In [ ]:
# 8-Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
tensor = tf.random.uniform(shape=(1,224,224,3))
# Squeeze
tf.squeeze(tensor).shape

TensorShape([224, 224, 3])

In [ ]:
# 9-Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor = tf.random.normal(shape=[10])
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=1.80325>

In [ ]:
# 10-One-hot encode the tensor you created in 9.
tf.one_hot(tensor.numpy(), depth=10)

# we convert it into numpy as one_hot accept numpy arrays

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# tf.one_hot(list_1, depth=4)